### ISSUE TITLE
The point of self.target_fc?

### ISSUE THREAD

**Issue by georgeadam** [SSARCandy/DeepCORAL#15]
Hi,

I was using the code from [models.py](https://github.com/SSARCandy/DeepCORAL/blob/master/models.py) to try and improve transfer learning results between two datasets. It made me wonder what the point of `self.target_fc` is  in the `DeepCORAL` class since it is never actually used in the forward pass. Instead, `self.source_fc' is applied to both the source and target data.

Also, in [main.py](https://github.com/SSARCandy/DeepCORAL/blob/master/main.py) the `test` function has a  `mode` argument which selects the output to return. Given the fact that it calls `model(data, data)` and that there is no difference between how these two inputs will be processed, is such indexing redundant?

**Comment by SSARCandy** [comment]
You are correct, those are legacy codes, going to clean it up, thanks.
