### ISSUE TITLE
range of the CORAL Loss

### ISSUE THREAD

**Issue by WERush** [SSARCandy/DeepCORAL#6]
Hi, when I train my network with CORAL loss, I find the CORAL Loss is extremely small, such as 1e-9 * 3.12 ..... 
Is it normal?

I want to know your CORAL loss range, thanks.

**Comment by SSARCandy** [comment]
I think that's not normal 
In A -> W task, my CORAL loss is about  ~0.0003

**Comment by WERush** [comment]
Another wired issue is that the CORAL loss increases with the training steps from 1e-9 to 1e-5.

Have you normalized the image from 0-255 to 0-1?

**Comment by SSARCandy** [comment]
Yes, I did normalize image to 0~1
